# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Selenium Tests

on:
  push:
    branches: [ test-without-failures ]
  pull_request:
    branches: [ test-without-failures ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: test-without-failures
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install selenium
    - name: Install Chrome
      run: |
        sudo apt-get -y update
        sudo apt-get -y install google-chrome-stable
    - name: Install Chrome Driver
      run: | 
        wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        rm chromedriver_linux64.zip
        mv chromedriver .local/bin/chromedriver
        sudo chmod 0755 .local/bin/chromedriver
    - run: ls
    - run: python3 python/p59-search.py test
    - run: python3 python/p59-sign-in.py test
    - run: python3 python/p59-setting.py test
    - run: python3 python/p59-reset-pwd.py test
    - run: python3 python/p59-favorite.py test
