# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Selenium Tests

on:
  push:
    branches: [ test-without-failures ]
  pull_request:
    branches: [ test-without-failures ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: joyzoursky/python-chromedriver:3.8-selenium
    steps:
    - uses: actions/checkout@v2
      with:
        ref: test-without-failures
    - name: Upgrade Pip
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest --ci
