# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ test-without-failures ]
  pull_request:
    branches: [ test-without-failures ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        python -m pip install --upgrade pip
        pip install selenium
        /opt/bin/entry_point.sh &
        sleep 5
    
    - run: python3 tests/p59-search.py -h test
    - run: python3 tests/p59-sign-in.py -h test
    - run: python3 tests/p59-setting.py -h test
    - run: python3 tests/p59-reset-pwd.py -h test
    - run: python3 tests/p59-favorite.py -h test
